yasuhisa1984/dive-23-10

Gemfile

ogata first commit

---

.gitignore

done "set gitignore"

---

app/controllers/questions_controller.rb
app/views/questions/index.html.erb

#6 
・questions_controllerのindexメソッドに追記
・view/questions/indexを修正

【Fixed】add Questions index

---

app/controllers/questions_controller.rb
app/views/questions/new.html.erb

#7 
questions_controller
・newメソッド、ストロングパラメータ用メソッド追加
・createメソッドで質問が作成されるよう修正
views/questions/new
・ファイルを作成
#6とコンフリクト起こしてみようとしたけどAble to merge. These branches can be automatically mergedになるのはなぜだろう？

【Fixed】Issues/#7

---

app/controllers/users_controller.rb
app/views/users/show.html.erb

マイページを作成しました。
こまめにプルリクしていなかったので、いらない機能まで
つけてたらどうしようと思い、不安になってます( ；∀；)。
プロフィールの画像はまだ着手してません。
もし、OKでした次はプロフィール画像をやりたいです。

add users/show and controllers/users_controller.rb

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

#40 の対応でサインアップ画面にユーザー名記入フォーム追加しました。ついでにユーザ編集画面にも追加しました。
また、deviseがname fieldの認識できるようにapplication_controller.rbも更新しました。

add name field on sign_up and user edit views

---

app/assets/stylesheets/common.scss
app/views/layouts/application.html.erb

#5
・全体のレイアウトを調整（スタイル追記のためcommon.scssを追加）
・ナビゲーションを追加
・表示サンプル

【Fixed】ナビゲーションを追加、全体のレイアウト調整

---

app/controllers/questions_controller.rb
app/helpers/questions_helper.rb
app/views/questions/edit.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb

作成しました。
issue: #9 #10 
PS
一覧画面にも項目追加しちゃいました。

質問詳細と編集画面作成、またそれに伴うcontrollerの編集と一覧画面にユーザー名と更新日付を追加

---

app/controllers/answers_controller.rb
app/controllers/questions_controller.rb
app/views/answers/_form.html.erb
app/views/answers/_index.html.erb
app/views/questions/show.html.erb
config/routes.rb

#11 
questions/showに部分テンプレートとして実装
issueは回答フォームだけでしたがフォームがあって回答一覧がないのもあれなので一緒に作っています。

回答フォーム＆回答一覧作成

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/controllers/favorites_controller.rb
app/helpers/favorites_helper.rb
app/models/question.rb
app/views/favorites/_favorite_button.html.erb
app/views/favorites/create.js.erb
app/views/favorites/destroy.js.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
config/routes.rb

星マークが欲しかったので、gemを入れました。
また、質問一覧画面と質問詳細画面に★ボタン追加しました。(layoutはまだ何もしてないっす)

font awesome gemのインストールとお気に入りボタンを質問の出力に加えた

---

app/controllers/favorites_controller.rb
app/views/favorites/index.html.erb

#16 
お気に入り画面のベース作成。
（最低限しか表示させていないので、追加対応が必要です。。）
※質問タイトルと質問へのリンクを表示

Fix favorite index (Add title and link to questions

---

db/migrate/20170526102511_add_index_user_id_and_question_id_to_favorites.rb
db/schema.rb

#67 の重複防止対応入れました。これでfavoriteがだぶるの防止できていると思います。
この対応が含まれないと
#65 がたまに重複で出ちゃいます。
もっといい方法あれば教えてください>_<

create unqiue index table to favorites

---

app/views/answers/_index.html.erb
app/views/questions/show.html.erb
db/seeds.rb

答えも引っ張ってこれました！
それに伴い、質問詳細のanswerのcontentsもsimple_formatつけました。

答えも引っ張ってくるようにseed.rbを更新

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/models/question.rb
app/models/tag.rb
app/models/tagging.rb
app/views/questions/new.html.erb
db/migrate/20170527041830_create_taggings.rb
db/schema.rb
spec/factories/taggings.rb
spec/models/tagging_spec.rb

gem と中間model作成したら, 編集file多くなったので一旦pull request投げます
reviewは新規質問画面よりformが出てたらOKとしていただければと思います。中の実装はこれからです

tagとquestionの中間table作成とbootstrap-tagsinput-rails gemをインストール

---

app/views/questions/index.html.erb

#69 
ユーザ詳細はanswers controllerの`routes.rb`が変更になったため、errorで落ちます
#62 で改善っすね、よろしくお願いします。

質問一覧にユーザー詳細と質問詳細への画面をつけました

---

app/helpers/application_helper.rb
app/views/users/show.html.erb

・プロフィールの画像を追加しました。
・routerに対応した、linkのPATHに修正しました。

fix /users/show.html.erb

---

app/assets/javascripts/tags.coffee
app/assets/stylesheets/tags.scss
app/controllers/questions_controller.rb
app/controllers/tags_controller.rb
app/helpers/tags_helper.rb
app/models/tag.rb
app/views/questions/index.html.erb
app/views/questions/new.html.erb
app/views/questions/show.html.erb
app/views/tags/_tag_list.html
app/views/tags/index.html.erb
config/routes.rb
db/migrate/20170527072151_rename_type_to_name_on_tags.rb
db/schema.rb
spec/controllers/tags_controller_spec.rb
spec/helpers/tags_helper_spec.rb
spec/views/tags/index.html.erb_spec.rb

tag機能できました、実装のみでcommitしても良かったのですが、
質問一覧、詳細画面にもtagが出るようにしときました。
tagのcolumnの名前を`type`から`name`に変更もしました。なんと`type`はmethodが存在するようで
エラーになったためです >_<
また、競合しないため、タグ一覧画面を作っときました。

create tagging model, tag form and tags index

---

app/assets/stylesheets/favorites.scss
app/views/favorites/_favorite_button.html.erb

extract favorite button color parameter to scss

---

app/controllers/answers_controller.rb

fix answer controller auth

---

app/models/answer.rb
app/models/question.rb
app/models/user.rb
app/models/vote.rb
db/migrate/20170523121833_create_votes.rb
db/migrate/20170527133344_remove_vote_from_question.rb
db/migrate/20170527133435_remove_vote_from_answer.rb
db/schema.rb
spec/factories/votes.rb
spec/models/vote_spec.rb

・Answerとquesitonテーブルのvoteを削除
・Voteテーブルの作成をしました。

remove table answer quesiton and add vote table

---

db/schema.rb

fix schema again

---

app/models/vote.rb
db/migrate/20170528085036_change_answer_to_vote.rb
db/schema.rb

・voteモデルの表記をタイプミスしていたので修正いたしました。
・question_idとanswer_idの、NULLを格納する許可に修正しました。

fix vote_table

---

app/controllers/questions_controller.rb

質問一覧の順番を新規投稿順に修正

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/initializers/devise.rb
config/initializers/simple_form.rb

・https://dive-23-10.herokuapp.com/
にアップしました。
・config/initializers/simple_form.rbがないと、herokuでアップする際にエラーが表示されるので
追加しました。
・Gemfileにruby '2.3.1'を追加することで、Herokuのrubyのversionを指定できました。

config heroku

---

app/views/favorites/index.html.erb

・お気に入り一覧画面で、お気に入りが0件の場合に、「お気に入りは0件です」などの表示を出す

Fix favorites/index.html.erb

---

app/assets/stylesheets/questions.scss
app/views/questions/new.html.erb
config/locales/model.ja.yml

質問新規を似せました。
あと、localeでmodel.ja.yml追加しました！

change new question view design

---

app/assets/stylesheets/application.css
app/views/answers/_form.html.erb
app/views/answers/_index.html.erb
app/views/layouts/application.html.erb
app/views/questions/show.html.erb

#116 
#120で指摘もらって再考しました。
container-fruidなしでcol12でそれっぽい幅になったのでこれで行こうと思います。。

Issues/#116 質問詳細画面デザイン

---

app/controllers/tags_controller.rb
app/views/tags/_tag_list.html
app/views/tags/show.html.erb
config/routes.rb

@yasuhisa1984  タグ詳細最低限だけ作っときました！
質問一覧のpartialできたらくっつけて整えてください ^ ^

タグ一覧とタグ詳細の骨組み作成

---

app/views/layouts/application.html.erb

ナビバーにタグ一覧を追加

---

app/controllers/votes_controller.rb
app/views/answers/_index.html.erb
app/views/questions/show.html.erb
app/views/votes/_vote_answer.html.erb
app/views/votes/_vote_question.html.erb
app/views/votes/create.html.erb
app/views/votes/destroy.html.erb
app/views/votes/vote_answer.js.erb
app/views/votes/vote_question.js.erb

#121 
#126 
github上で修正しようとしたらおかしなことになってたみたいです。

質問詳細画面の表示崩れを修正

---

app/controllers/application_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/registrations_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
config/initializers/devise.rb
config/routes.rb
db/migrate/20170602024129_add_omniauth_columns_to_users.rb
db/schema.rb

.envに以下を追加するとログインできるようにしました。
FACEBOOK_ID_DEVELOPMENT=
FACEBOOK_SECRET_DEVELOPMENT=
TWITTER_ID_DEVELOPMENT=
TWITTER_SECRET_DEVELOPMENT=
(Callback URLはローカルホストにしています。)
achiveと同じでログインできると思います。

SNSログインを実装

---

db/seeds.rb

対応しました。
db:resetしても
SEED_USER_EMAIL
SEED_USER_PASSWORD
でloginできます

dummy userでlogin可能

---

app/controllers/users_controller.rb

・includes(:question)するとbulletで検知されなくなりました。

N + 1問題　ユーザー詳細画面

---

app/views/questions/show.html.erb

#119 
current_userとquestion useridが異なる場合はボタン自体を表示しない
ついでに編集削除戻るをボタン化

【Fixed】他人の質問を編集、削除できないようにする

---

app/controllers/questions_controller.rb

N + 1 問題　質問一覧画面

---

app/assets/stylesheets/tags.scss
app/controllers/favorites_controller.rb
app/controllers/ranking_controller.rb
app/controllers/tags_controller.rb
app/views/favorites/index.html.erb
app/views/ranking/index.html.erb
app/views/tags/show.html.erb

デザイン【ランキング一覧とお気に入り一覧とタグの詳細】

---

app/views/devise/registrations/edit.html.erb
app/views/questions/edit.html.erb
app/views/questions/new.html.erb
app/views/questions/show.html.erb

戻るボタン削除
・ユーザー詳細
・新規・編集質問画面
・ユーザー編集

Delete back btn　戻るボタン削除

---

app/views/users/show.html.erb

Fix display date

---

app/models/user.rb

画面はいじってません、user validationをつけるとsimple_form化はされてるのでつきました！

ユーザー編集画面に項目必須マークをつけるようにしました

---

app/controllers/answers_controller.rb
app/views/answers/_form.html.erb
app/views/answers/_index.html.erb
app/views/answers/edit.html.erb

add answer update/destroy function

---

app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb

Fix mail texts メールテキストを日本語化

---

app/views/answers/_form.html.erb
app/views/answers/_index.html.erb
app/views/questions/show.html.erb
app/views/tags/show.html.erb

#151 
・質問詳細画面の回答のボタンを修正
・質問詳細画面のユーザーからリンクを貼る
・tags/show.html.erbの閉じタグ修正

質問詳細画面にてuserのlink付けと不要な文字列削除 

---

app/views/answers/_form.html.erb

Fix when login ログイン時に回答フォーム非表示

---

app/assets/stylesheets/users.scss
app/views/users/show.html.erb

Fix link, and Style　ユーザー編集の回答リンク先を修正
